// <auto-generated />
namespace ToDoList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Status_Added_To_ToDoTasks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Status_Added_To_ToDoTasks));
        
        string IMigrationMetadata.Id
        {
            get { return "201808162200414_Status_Added_To_ToDoTasks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
