// <auto-generated />
namespace ToDoList.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add5Tasks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add5Tasks));
        
        string IMigrationMetadata.Id
        {
            get { return "201809071621417_Add5Tasks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
